title: Daya Babu Chinthaguntla # your name (or website title) here
logo: "/profile.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
 Aspiring DevOps Engineer
  <br><br>
  <a href="mailto:dayababujohn@gmail.com">dayababujohn@gmail.com </a>
  <br>
  <a href="https://www.linkedin.com/in/daya-babu-chinthaguntla/">LinkedIn Profile</a>
  <br>
  <a href="https://www.gihub.com/dayasanjay/">Gihub</a> 
theme: jekyll-theme-minimal
